### ISSUE TITLE
Feature Request - Ability to set SPU hostname

### ISSUE THREAD

**Issue by username-is-already-taken2** [Nebulon/NebulonON-Collection#1]
Hi there

Could you add support to allow to set the hostname of a SPU please

Like this in the UI
![image](https://user-images.githubusercontent.com/13700297/183108451-a6963e42-c265-40e4-83bc-e6633c9a716f.png)

Thank you

**Comment by ghost** [comment]
Thanks for the feature request, Gary. I talked to the team and we'll add the feature in our upcoming release.

**Comment by ghost** [comment]
This will be delivered in an upcoming 1.3.0 release of the collection. The plan is to allow setting and unsetting the host display name and the note property.

**Comment by ghost** [comment]
Nebulon ON Collection version 1.3.0 was just released :rocket: and it includes this feature request.
